import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { AOSInit } from "@/components/Aos"
import Header from "@/components/Header"
import Container from "@/layouts/Container"
import { cn } from "@/lib/utils"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    default: "Green Phoenix",
    template: `%s | Green Phoenix`,
  },
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={cn(inter.className, "w-full h-screen bg-slate-50 flex flex-col p-10")}>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  )
}
